_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.1
            "6": 4.47.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
dataset:
    value: c4
model:
    value: /home/liukunlong/lkl_model/llama/Llama-2-7b-hf
